// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjvnqsmsbyjhuftjbval.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqdm5xc21zYnlqaHVmdGpidmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODUyNTIsImV4cCI6MjA2OTU2MTI1Mn0.Ewn6BVAbS1OXdSOX-Q7fCNmS6qzrq--rypaMtbaIb9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});